#! /bin/sh

run () { ! pgrep -x "$1" > /dev/null && "$@"; }

bspc monitor -d     

bspc config border_width         0
bspc config window_gap          12


bspc config normal_border_color "#58a6ff"
bspc config active_border_color "#58a6ff"
bspc config focused_border_color "#bf9ae9"
bspc config presel_feedback_color "#bf9ae9"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config automatic_scheme	spiral

xsetroot -cursor_name left_ptr

bspc rule -a St desktop=^1 state=floating rectangle=400x400+400+400  follow=on
bspc rule -a Chromium desktop='^2'

run sxhkd & 
run picom & 
run polybar & 
run dunst & feh --bg-scale /home/uwo/.config/bspwm/arch-chan_to.png & 
run xsettingsd &
run unclutter --timeout 3 &
