#! /bin/sh



sxhkd & picom & nitrogen --restore & polybar &



bspc monitor -d     


bspc config border_width         1
bspc config window_gap          12


bspc config normal_border_color "#58a6ff"
bspc config active_border_color "#58a6ff"
bspc config focused_border_color "#bf9ae9"

bspc config presel_feedback_color "#bf9ae9"



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config automatic_scheme	spiral

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a termite state=floating rectangle=400x400+400+400  follow=off
bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
